# Generated by Django 4.0.1 on 2022-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_like_delete_likes_rename_user_id_post_user_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
